//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstTest_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Accounting_Fe_Instrument
    {
        public string QctKey { get; set; }
        public string FriendlyName { get; set; }
        public int SequenceNumber { get; set; }
        public string Exchange { get; set; }
        public string CommodityType { get; set; }
        public string Contract { get; set; }
        public Nullable<decimal> ContractMultiplier { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.DateTime> StartTradingDate { get; set; }
        public Nullable<System.DateTime> EndTradingDate { get; set; }
        public string InstrumentCategory { get; set; }
        public short SpecialInstrumentType { get; set; }
        public Nullable<System.DateTime> PromptDate { get; set; }
        public Nullable<System.DateTime> CurrentStartDate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
    }
}
