//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstTest_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Accounting_Fe_Currency
    {
        public string QctKey { get; set; }
        public string FriendlyName { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<short> Scale { get; set; }
        public string UnitName { get; set; }
        public string Symbol { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
    }
}
