//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstTest_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Accounting_Fe_InstrumentCategory
    {
        public string QctKey { get; set; }
        public string ContractCode { get; set; }
        public string FriendlyName { get; set; }
        public int SequenceNumber { get; set; }
        public string Exchange { get; set; }
        public string CommodityType { get; set; }
        public string Currency { get; set; }
        public Nullable<int> FinancialInstrumentType { get; set; }
        public Nullable<int> InstrumentPeriodType { get; set; }
        public Nullable<decimal> ContractMultiplier { get; set; }
        public string CargoUnit { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> MinPriceChange { get; set; }
        public Nullable<decimal> PriceMultiplier { get; set; }
        public string ContractFormat { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
    }
}
