//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstTest_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Accounting_Fe_TradeAccount
    {
        public string QctKey { get; set; }
        public string FriendlyName { get; set; }
        public int SequenceNumber { get; set; }
        public string AccountType { get; set; }
        public string Corporation { get; set; }
        public string AccountCurrency { get; set; }
        public string Broker { get; set; }
        public bool IsVirtual { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public bool Disabled { get; set; }
        public int Indicator { get; set; }
    }
}
