//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirstTest_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInvoiceDetailQuantity
    {
        public int WFInvoiceDetailQuantityId { get; set; }
        public Nullable<int> WFContractInvoiceId { get; set; }
        public bool IsComponentMainQuantity { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Taxation { get; set; }
        public Nullable<decimal> FinalQuantity { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
    
        public virtual WFContractInvoice WFContractInvoice { get; set; }
    }
}
